platform :ios, '13.0'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'Plugin' do
  capacitor_pods
  pod 'SQLCipher', '~>4.5.6'
  pod 'ZIPFoundation', '~> 0.9.18'
end

target 'PluginTests' do
  capacitor_pods
  pod 'SQLCipher', '~>4.5.6'
  pod 'ZIPFoundation', '~> 0.9.18'
end

