name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  NODE_VERSION: 18
  JAVA_VERSION: 17

jobs:
  build:
    name: Build
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Build iOS
        run: npm run verify:ios
      - name: Build Android
        run: npm run verify:android
      - name: Build Web
        run: npm run verify:web
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  lint:
    name: Lint
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Run Lint script
        run: npm run lint
