name: Remove needs-reply label

on:
  issue_comment:
    types:
      - created

permissions:
  issues: write

jobs:
  needs-reply:
    runs-on: ubuntu-latest
    if: github.repository == 'capacitor-community/sqlite' && github.event.comment.author_association != 'MEMBER'
    steps:
      - name: Remove needs-reply label
        run: |
          curl --request DELETE \
          --url 'https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels/needs%3A%20reply' \
          --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}'
